# If you modify this file, you need to recompile.

[bl_default]
ic3 = "-e ic3 --rseed 1"
ic3_no_preproc = "-e ic3 --ic3-ctg=false --frts=false --scorr=false --ic3-drop-po=false --rseed 2"
ic3_no_parent = "-e ic3 --ic3-drop-po=false --ic3-parent-lemma=false --rseed 3"
ic3_abs_cst = "-e ic3 --ic3-abs-cst --rseed 4"
ic3_abs_all = "-e ic3 --ic3-abs-cst --ic3-abs-trans --rseed 5"
ic3_dynamic = "-e ic3 --ic3-abs-cst --ic3-abs-trans --ic3-dynamic --ic3-drop-po=false --rseed 6"
ic3_ctg_limit = "-e ic3 --ic3-ctg-max 5 --ic3-ctg-limit 15 --ic3-drop-po=false --rseed 7"
ic3_inn = "-e ic3 --ic3-inn --rseed 8"
ic3_inn_ctp = "-e ic3 --ic3-inn --ic3-ctp --rseed 9"
ic3_inn_noctg = "-e ic3 --ic3-inn --ic3-ctg=false --rseed 10"
ic3_inn_dynamic = "-e ic3 --ic3-inn --ic3-dynamic --ic3-drop-po=false --rseed 11"
bmc = "-e bmc --step 1 --rseed 12"
bmc_kissat_10 = "-e bmc --bmc-kissat --step 10 --rseed 13"
bmc_kissat_65 = "-e bmc --bmc-kissat --step 65 --rseed 14"
bmc_kissat_dyn = "-e bmc --bmc-kissat --bmc-dyn-step --rseed 15"
kind = "-e kind --step 1 --rseed 16"

[wl_default]
ic3 = "-e ic3 --rseed 1"
ic3_no_preproc = "-e ic3 --ic3-ctg=false --frts=false --scorr=false --ic3-drop-po=false --rseed 2"
ic3_no_parent = "-e ic3 --ic3-drop-po=false --ic3-parent-lemma=false --rseed 3"
ic3_abs_cst = "-e ic3 --ic3-abs-cst --rseed 4"
ic3_abs_all = "-e ic3 --ic3-abs-cst --ic3-abs-trans --rseed 5"
ic3_dynamic = "-e ic3 --ic3-abs-cst --ic3-abs-trans --ic3-dynamic --ic3-drop-po=false --rseed 6"
ic3_ctg_limit = "-e ic3 --ic3-ctg-max 5 --ic3-ctg-limit 15 --ic3-drop-po=false --rseed 7"
ic3_inn = "-e ic3 --ic3-inn --rseed 8"
ic3_inn_ctp = "-e ic3 --ic3-inn --ic3-ctp --rseed 9"
ic3_inn_noctg = "-e ic3 --ic3-inn --ic3-ctg=false --rseed 10"
ic3_inn_dynamic = "-e ic3 --ic3-inn --ic3-dynamic --ic3-drop-po=false --rseed 11"
bmc = "-e bmc --step 1 --rseed 12"
bmc_kissat_10 = "-e bmc --bmc-kissat --step 10 --rseed 13"
bmc_kissat_dyn = "-e bmc --bmc-kissat --bmc-dyn-step --rseed 14"
wlbmc = "-e wl-bmc --rseed 15"
wlkind = "-e wl-kind --step 1 --rseed 16"

[bl_hwmcc]
ic3 = "-e ic3 --rseed 1"
ic3_no_preproc = "-e ic3 --ic3-ctg=false --frts=false --scorr=false --ic3-drop-po=false --rseed 2"
ic3_no_parent = "-e ic3 --ic3-drop-po=false --ic3-parent-lemma=false --rseed 3"
ic3_abs_cst = "-e ic3 --ic3-abs-cst --rseed 4"
ic3_abs_all = "-e ic3 --ic3-abs-cst --ic3-abs-trans --rseed 5"
ic3_dynamic = "-e ic3 --ic3-abs-cst --ic3-abs-trans --ic3-dynamic --ic3-drop-po=false --rseed 6"
ic3_ctg_limit = "-e ic3 --ic3-ctg-max 5 --ic3-ctg-limit 15 --ic3-drop-po=false --rseed 7"
ic3_inn = "-e ic3 --ic3-inn --rseed 8"
ic3_inn_ctp = "-e ic3 --ic3-inn --ic3-ctp --rseed 9"
ic3_inn_noctg = "-e ic3 --ic3-inn --ic3-ctg=false --rseed 10"
ic3_inn_dynamic = "-e ic3 --ic3-inn --ic3-dynamic --ic3-drop-po=false --rseed 11"
bmc = "-e bmc --step 1 --rseed 12"
bmc_kissat_10 = "-e bmc --bmc-kissat --step 10 --rseed 13"
bmc_kissat_65 = "-e bmc --bmc-kissat --step 65 --rseed 14"
bmc_kissat_dyn = "-e bmc --bmc-kissat --bmc-dyn-step --rseed 15"
kind = "-e kind --step 1 --rseed 16"
