# If you modify this file, you need to recompile.

[bl_default]
ic3 = "ic3 --rseed 1"
ic3_no_preproc = "ic3 --ctg=false --frts=false --scorr=false --drop-po=false --rseed 2"
ic3_no_parent = "ic3 --drop-po=false --parent-lemma=false --rseed 3"
ic3_abs_cst = "ic3 --abs-cst --rseed 4"
ic3_abs_all = "ic3 --abs-cst --abs-trans --rseed 5"
ic3_dynamic = "ic3 --abs-cst --abs-trans --dynamic --drop-po=false --rseed 6"
ic3_ctg_limit = "ic3 --ctg-max 5 --ctg-limit 15 --drop-po=false --rseed 7"
ic3_inn = "ic3 --inn --rseed 8"
ic3_inn_ctp = "ic3 --inn --ctp --rseed 9"
ic3_inn_noctg = "ic3 --inn --ctg=false --rseed 10"
ic3_inn_dynamic = "ic3 --inn --dynamic --drop-po=false --rseed 11"
bmc = "bmc --step 1 --rseed 12"
bmc_kissat_10 = "bmc --kissat --step 10 --rseed 13"
bmc_kissat_65 = "bmc --kissat --step 65 --rseed 14"
bmc_kissat_dyn = "bmc --kissat --dyn-step --rseed 15"
kind = "kind --step 1 --rseed 16"

[wl_default]
ic3 = "ic3 --rseed 1"
ic3_no_preproc = "ic3 --ctg=false --frts=false --scorr=false --drop-po=false --rseed 2"
ic3_no_parent = "ic3 --drop-po=false --parent-lemma=false --rseed 3"
ic3_abs_cst = "ic3 --abs-cst --rseed 4"
ic3_abs_all = "ic3 --abs-cst --abs-trans --rseed 5"
ic3_dynamic = "ic3 --abs-cst --abs-trans --dynamic --drop-po=false --rseed 6"
ic3_ctg_limit = "ic3 --ctg-max 5 --ctg-limit 15 --drop-po=false --rseed 7"
ic3_inn = "ic3 --inn --rseed 8"
ic3_inn_ctp = "ic3 --inn --ctp --rseed 9"
ic3_inn_noctg = "ic3 --inn --ctg=false --rseed 10"
ic3_inn_dynamic = "ic3 --inn --dynamic --drop-po=false --rseed 11"
bmc = "bmc --step 1 --rseed 12"
bmc_kissat_10 = "bmc --kissat --step 10 --rseed 13"
bmc_kissat_dyn = "bmc --kissat --dyn-step --rseed 14"
wlbmc = "wl-bmc --rseed 15"
wlkind = "wl-kind --step 1 --rseed 16"

[bl_hwmcc]
ic3 = "ic3 --rseed 1"
ic3_no_preproc = "ic3 --ctg=false --frts=false --scorr=false --drop-po=false --rseed 2"
ic3_no_parent = "ic3 --drop-po=false --parent-lemma=false --rseed 3"
ic3_abs_cst = "ic3 --abs-cst --rseed 4"
ic3_abs_all = "ic3 --abs-cst --abs-trans --rseed 5"
ic3_dynamic = "ic3 --abs-cst --abs-trans --dynamic --drop-po=false --rseed 6"
ic3_ctg_limit = "ic3 --ctg-max 5 --ctg-limit 15 --drop-po=false --rseed 7"
ic3_inn = "ic3 --inn --rseed 8"
ic3_inn_ctp = "ic3 --inn --ctp --rseed 9"
ic3_inn_noctg = "ic3 --inn --ctg=false --rseed 10"
ic3_inn_dynamic = "ic3 --inn --dynamic --drop-po=false --rseed 11"
bmc = "bmc --step 1 --rseed 12"
bmc_kissat_10 = "bmc --kissat --step 10 --rseed 13"
bmc_kissat_65 = "bmc --kissat --step 65 --rseed 14"
bmc_kissat_dyn = "bmc --kissat --dyn-step --rseed 15"
kind = "kind --step 1 --rseed 16"
